trigger:
- master
- develop

stages:
- stage: Acceptance
  displayName: Acceptance stage
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
  pool: 
    vmImage: 'ubuntu-latest'
  jobs:
  - job: Build

  - job: Deploy



- stage: Production
  displayName: Production stage
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  pool: 
    vmImage: 'ubuntu-latest'
  jobs:
  - job: Build
    steps:

    - script: |
        npm install
        gulp default --gulpfile gulpfile.js
      displayName: 'npm install and run gulp'

    - task: CopyFiles@2
      inputs:
        Contents: |
          js/*min*
          css/*min*
          vendor/**
          img/**
          favicon.ico
          index.html
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        CleanTargetFolder: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)' 
        ArtifactName: 'build-output' 

  - job: Deploy
    condition: succeeded()
    displayName: Deploy to release branch
    pool: 
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'build-output'
        downloadPath: '$(System.ArtifactsDirectory)'

    - powershell: |
        Write-Host "Adding artifact directory: $(System.ArtifactsDirectory)"
        git add "$(System.ArtifactsDirectory)"
        Write-Host "Set user.name to Pipeline"
        git config user.name "Pipeline"
        Write-Host "Commit changes"
        git commit -m "Push build to release branch"
        Write-Host "Push the commit to origin release"
        git push --set-upstream origin release
