trigger:
- feature/*
- master

resources:
  repositories:
  - repository: github_pages
    type: github
    name: machielvisser/machielvisser.github.io
    endpoint: machielvisser
    ref: github

stages:
- stage: Test
  displayName: Dev/Test stage
  condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/')
  pool: 
    vmImage: 'ubuntu-latest'
  jobs:
  - job: TestBuild
    steps:
    - template: templates/build.yml

  - deployment: TestDeployment
    dependsOn: TestBuild
    condition: in(dependencies.TestBuild.result, 'Succeeded')
    displayName: Deploy the Test Infrastructure
    pool: 
      vmImage: 'windows-2019'
    environment: 'website-test-environment'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/deployToStorageAccount.yml

- stage: Production
  displayName: Production stage
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  pool: 
    vmImage: 'ubuntu-latest'
  jobs:
  - job: ProductionBuild
    steps:
    - template: templates/build.yml

  - deployment: ProductionDeployment
    dependsOn: ProductionBuild
    condition: in(dependencies.ProductionBuild.result, 'Succeeded')
    displayName: Deploy to release branch
    pool: 
      vmImage: 'ubuntu-latest'
    environment: 'github-pages'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/deployToGitHub.yml
