# Node.js with gulp
# Build a Node.js project using the gulp task runner.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- develop
- feature/*
- release/*

stages:
  - stage: Build
    displayName: Production build    
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    pool: 
      vmImage: 'ubuntu-latest'
    jobs:
    - job:
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

      - script: |
          npm install
          gulp default --gulpfile gulpfile.js
        displayName: 'npm install and run gulp'

      - task: CopyFiles@2
        inputs:
          contents: |
            js\*
            css\*
            vendor\*
            img\*
            favicon.ico
            index.html
          targetFolder: $(Build.ArtifactStagingDirectory)

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
          artifactName: 'build-output' 


