trigger:
- feature/*
- master

resources:
  repositories:
  - repository: github_pages
    type: github
    name: machielvisser/machielvisser.github.io
    endpoint: machielvisser
    ref: github

stages:
- stage: Production
  displayName: Production
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  pool: 
    vmImage: 'ubuntu-latest'
  jobs:
  - job: ProductionBuild
    steps:
    - template: templates/build.yml

  - deployment: ProductionDeployment
    dependsOn: ProductionBuild
    condition: in(dependencies.ProductionBuild.result, 'Succeeded')
    displayName: Deploy to release branch
    pool: 
      vmImage: 'ubuntu-latest'
    environment: 'github-pages'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/deployToGitHub.yml
