steps:
  - script: |
      npm install
      gulp default --gulpfile gulpfile.js
    displayName: 'npm install and run gulp'
  - task: CopyFiles@2
    inputs:
      Contents: |
        js/*min*
        css/*min*
        vendor/**
        img/**
        deployment/**
        favicon.ico
        *.html
        CNAME
        LICENSE
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      CleanTargetFolder: true

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'build-output'
      publishLocation: 'pipeline'
