steps:
  - script: |
      npm install
      npm run build
    displayName: Build
  - task: CopyFiles@2
    displayName: Copy to staging directory
    inputs:
      Contents: |
        js/*min*
        css/*min*
        vendor/**
        img/**
        deployment/**
        favicon.ico
        *.html
        CNAME
        LICENSE
        .well-known/**
        _config.yml
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      CleanTargetFolder: true

  - task: PublishPipelineArtifact@1
    displayName: Publish pipeline artifacts
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'build-output'
      publishLocation: 'pipeline'
