name: deploy to github branch
on: push
permissions:
  contents: write
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            js/*min*
            css/*min*
            vendor/**
            img/**
            deployment/**
            favicon.ico
            *.html
            CNAME
            LICENSE
            .well-known/**
            _config.yml
  production:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'github'
          path: ./target
      - name: Removing unnecessary files
        run: |
          rm -r target/*
      - uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ./build-output        
      - run: cp -v -r build-output/* target/
      - name: Commit build
        working-directory: ./target
        run: |
          pwd
          git config user.name "Pipeline"
          git config user.email "dummy@domain.com"
          git add --all
          git commit -m "Push build to github branch"
          git push origin github
