name: cd
    
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            js/*min*
            css/*min*
            vendor/**
            img/**
            deployment/**
            favicon.ico
            *.html
            CNAME
            LICENSE
            .well-known/**
            _config.yml
  production:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        name: Download build output
        with:
          name: build-output
          path: public
      - name: setup hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: '0.108.0'
      - name: deploy to s3
        run: hugo deploy --force --maxDeletes -1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_ACCESS_KEY }}
